### ISSUE TITLE
请教个less样式问题

### ISSUE THREAD

**Issue by wangs1203** [Lands-1203/antd-react-components#2]
样式bundless 并不会打包，项目中组件库的less文件怎么处理

**Comment by Lands-1203** [comment]
我不太理解问题出在那个地方，目前样式文件没多少内容 可以暂时忽略的

**Comment by wangs1203** [comment]
> 我不太理解问题出在那个地方，目前样式文件没多少内容 可以暂时忽略的

在项目中（css采用styled-components）引用@lands/antd-react-components内的组件，例如ProTableEdit，是没有样式的，less文件并没有被编译，father4 esm和cjs bundless打包不会处理less。请教下实际在项目中，怎么配置能处理组件库的样式

**Comment by wangs1203** [comment]
> > 我不太理解问题出在那个地方，目前样式文件没多少内容 可以暂时忽略的
> 
> 在项目中（css采用styled-components）引用@lands/antd-react-components内的组件，例如ProTableEdit，是没有样式的，less文件并没有被编译，father4 esm和cjs bundless打包不会处理less。请教下实际在项目中，怎么配置能处理组件库的样式

在项目中试着配置了less-loader的处理，loader配置加了includes node_modules，但也并没有处理组件库内的less，跑项目还是没有样式

**Comment by Lands-1203** [comment]
less-loader生效了吗？本地写一个less文件引入尝试一下

**Comment by Lands-1203** [comment]
客户端引用antd或者antd pro组建默认是没有样式文件的，需要自己单独import 你看看自己antd的组件样式是否加载成功？

**Comment by Lands-1203** [comment]
如果解决不了 我首页有我的邮件地址 可以将项目的demo发给我看下

**Comment by Lands-1203** [comment]
https://www.npmjs.com/package/@lands-pro/antd-react-components
![image](https://github.com/Lands-1203/antd-react-components/assets/61341868/3f0fe828-2638-4c31-bfc3-899fbff398f5)
已经将项目中的所有less转换成了css 编译产物没有less了
注意：项目重新发布了一份在npm仓库，原私有仓库也发布了一份新的。由于npm仓库lands域名被占用，项目名修改成了：@lands-pro/antd-react-components@1.0.3
提交日志：https://github.com/Lands-1203/antd-react-components/commit/f6eea264f2fbd26e1e3788c3b01ec1f131759834

**Comment by Lands-1203** [comment]
father 只是 bundleless ，不会处理源代码里的非 TS 文件，只会拷贝到产物里对应位置，所有非 TS 源码的功能（如 less / css module 等），都需要引入这个库的主体项目来支持这些功能。

比如使用 antd 4 的时候，样式可以引入 antd.less ，但项目本身要支持 less 转译。如果需要 css 产物，应该选择 bundle 为单文件的打包器（如 father umd ，或 rollup 等）。

**Comment by wangs1203** [comment]
> https://www.npmjs.com/package/@lands-pro/antd-react-components ![image](https://private-user-images.githubusercontent.com/61341868/317186075-3f0fe828-2638-4c31-bfc3-899fbff398f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjkyODgsIm5iZiI6MTcxMjEyODk4OCwicGF0aCI6Ii82MTM0MTg2OC8zMTcxODYwNzUtM2YwZmU4MjgtMjYzOC00YzMxLWJmYzMtODk5ZmJmZjM5OGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmODRlNzhkZjUyMmQ1Y2QyZmNhMmY1YWVjMTk4NDM1ODJmNGQ4Yzg0NTMwY2VjOTllZmJjOTI2ZmU3OTNjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J7UCg2J0Wv97eAR6RH1-3CF4m6uLMa2ba2X_R63HJeM) 已经将项目中的所有less转换成了css 编译产物没有less了 注意：项目重新发布了一份在npm仓库，原私有仓库也发布了一份新的。由于npm仓库lands域名被占用，项目名修改成了：@lands-pro/antd-react-components@1.0.3 提交日志：[f6eea26](https://github.com/Lands-1203/antd-react-components/commit/f6eea264f2fbd26e1e3788c3b01ec1f131759834)

@Lands-1203 感谢大佬，学到了。

**Comment by wangs1203** [comment]
> father 只是 bundleless ，不会处理源代码里的非 TS 文件，只会拷贝到产物里对应位置，所有非 TS 源码的功能（如 less / css module 等），都需要引入这个库的主体项目来支持这些功能。
> 
> 比如使用 antd 4 的时候，样式可以引入 antd.less ，但项目本身要支持 less 转译。如果需要 css 产物，应该选择 bundle 为单文件的打包器（如 father umd ，或 rollup 等）。

还有个问题，希望大佬能解惑一二，感激不尽。

「 bundleless不会处理源代码里的非 TS 文件，只会拷贝到产物里对应位置」
那么我在主体项目中如果配置了less-loader，import SelectSquare组件时，SelectSquare组件中`import './styles.less';`是会被处理的吧？

```tsx
import { Select, SelectProps } from 'antd';
import React from 'react';
import './styles.less';

function SelectSquare(props: SelectProps) {
  return <Select {...props} showSearch virtual={false} />;
}
export default SelectSquare;
```


我在主体项目中试着配置了less-loader的处理，less-loader配置加了，loader options也加了includes: /node_modules/，但也并没有处理组件库内的less，跑项目还是没有组件库的less样式

**Comment by Lands-1203** [comment]
你项目的less 能加载吗？

**Comment by Lands-1203** [comment]
我不太清楚你的是用什么脚手架搭建的，在webpack中你只需要
```
    module: {
        rules: [
            {
                test: /\.less$/,
                use: [
                    'style-loader', 
                    'css-loader',   
                    'less-loader'  
                ],
            },
        ],
    },
```

**Comment by Lands-1203** [comment]
> 我不太清楚你的是用什么脚手架搭建的，在webpack中你只需要
> 
> ```
>     module: {
>         rules: [
>             {
>                 test: /\.less$/,
>                 use: [
>                     'style-loader', 
>                     'css-loader',   
>                     'less-loader'  
>                 ],
>             },
>         ],
>     },
> ```

确保执行了 `npm i less-loader less css-loader style-loader --save-dev `

**Comment by wangs1203** [comment]
> 你项目的less 能加载吗？

项目的less文件走了less-loader编译，跑起来html有样式，
就只有组件库内的`import './styles.less';`没有处理。很奇怪。
loader也都装了。

我在自己看看吧。
